"""
Data Analysis V3 State Management
Following AgenticDataAnalysis state.py pattern exactly
"""

import operator
from typing import Sequence, TypedDict, Annotated, List, Dict, Any
from langchain_core.messages import BaseMessage


class DataAnalysisState(TypedDict):
    """
    State structure for data analysis workflow.
    Follows AgenticDataAnalysis pattern with ChatMRPT adaptations.
    """
    # Conversation history - accumulates with operator.add
    messages: Annotated[Sequence[BaseMessage], operator.add]
    
    # Loaded datasets - dictionary of DataFrame names and metadata
    input_data: Dict[str, Any]
    
    # Intermediate outputs for debugging (hidden from users)
    intermediate_outputs: Annotated[List[dict], operator.add]
    
    # Current Python variables that persist between executions
    current_variables: dict
    
    # Plotly figure paths for visualization
    output_plots: Annotated[List[str], operator.add]
    
    # User-friendly insights generated from analysis
    insights: Annotated[List[str], operator.add]
    
    # Session information
    session_id: str
    
    # Error messages (converted to user-friendly format)
    errors: Annotated[List[str], operator.add]
    # Pending subtasks generated by planner
    pending_subtasks: Annotated[List[str], operator.add]
